### PR TITLE
fix break in readme formatting

### PR DESCRIPTION
**Pull request by vlakarados**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey, thanks for contribution.

This is actually 2 sections on purpose, because there are 2 rules in this sniff. Merging them together makes it more difficult to spot.

Do you have some idea to change it to make it more clear?

**Comment by vlakarados** [comment]
Hey, I see your point and it makes total sense, maybe it's best to separate them to two different examples?
One for avoiding public properties and the other for not using setters?

**Comment by TomasVotruba** [comment]
That would be the best :+1:

**Comment by TomasVotruba** [comment]
Closing for no reaction. Feel free to reopen with fix

**Pull request closed without merging**
