### PR TITLE
Removed package dependency

### PR DESCRIPTION
**Pull request by rohanvakharia**
I have removed packages dependency so that it can be used directly without composer install

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This is composer package, so it's designed to be used with composer install.

**Comment by rohanvakharia** [comment]
I haven't removed composer. I just removed package dependency so that it can be added as installed_paths in phpcs from anywhere.

**Comment by TomasVotruba** [comment]
I know. Yet changes kills dependency idea behind composer.

**Comment by TomasVotruba** [comment]
Bad design of PHP_CodeSniffer cannot make all ruleset remove dependencies.

**Comment by TomasVotruba** [comment]
I recommend using ECS, there is no such problem.

**Comment by rohanvakharia** [comment]
I will fix those phpcs errors, though I feel that remove those packages will open up additional and easy way to add this standard while coding. Users can add in the editor and check the calisthenics errors while coding itself

**Pull request closed without merging**
