### PR TITLE
[WIP] Exclude fluent interfaces from OneObjectOperatorPerLineSniff

### LINKED ISSUE #41: Question about Fluent Interfaces
Hi,

is there any way to get rid of the `Only one object operator per line.` errors when using the `Doctrine\DBAL\Query\QueryBuilder`?

### PR DESCRIPTION
**Pull request by UFOMelkor**
Allows the OneObjectOperatorPerLineSniff ignore fluent interfaces.

Fluent interfaces are recognized by its starting points. A starting point can be either a variable (like `$queryBuilder`) or a method call (like `createQueryBuilder()`).
In both cases the fluent interface might end before the end of the call chain. Therefore end points (like `getQuery()` will let the sniff work normally for the calls that are detected afterwards.

There are some things to clarify:
 - Should there are any defaults for the starting / end points? IMHO this is user specific, so no defaults would be the better way. (Didn't implemented it yet because it will make the test execution harder.)
 - Configuration of Sniffs is done by public properties, but this violates the object-calisthenics ruleset.

Closes #41

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This looks nice and clear. Thank you for the  PR!
What needs to be done here?

I'm about to add these sniffs to my code: https://github.com/Symplify/Symplify
So I should test them hard! :)

**Comment by UFOMelkor** [comment]
I would suggest the following steps:
 - Create another ruleset in `tests\rulesets.xml` that imports `src\ObjectCalisthenics\ruleset.xml` but excludes the `ObjectCalisthenics.Classes.PropertyVisibility` sniff.
 - Adjust the `composer.json` to use `tests\rulesets.xml` instead of `src\ObjectCalisthenics\ruleset.xml`.

Not really cool, but as long as PHP_CodeSniffer offers no other possibility to configure rules, we depend on public properties.

Next step would be thinking about defaults. The only fluent interfaces I use are the doctrine ones. But I'm sure there are a lot more (thinking e.g. of the Symfony Finder component).
Therefore I suggest using no defaults but add a documentation about how to configure it by yourself.

**Comment by TomasVotruba** [comment]
That's another issue, but I'm aware of it.

Actually I'm finishing layer above PHP_CodeSniffer that would allow writing rules in clean way. I like it the way PHP-CS-Fixer solves this via [`configure()` method](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/159708030d488200cb16b9440fd2883a0e5f74b8/src/Fixer/ArrayNotation/ArraySyntaxFixer.php#L52).

**Comment by UFOMelkor** [comment]
That sounds good to me. So next steps would be
- Add an exclude-pattern `*Sniff.php` to the rule `ObjectCalisthenics.Classes.PropertyVisibility`
- Remove default values and adjust the tests
- Document the configuration (perhaps [here](github.com/object-calisthenics/phpcs-calisthenics-rules#rule-4-use-only-one-object-operator-per-line)?)

**Comment by TomasVotruba** [comment]
@UFOMelkor I agree, let's do this. Could you prepare PR for that?

I'm about to simplify the README text, so normal people could read it with joy and understand it.

**Comment by TomasVotruba** [comment]
What needs to be done here related to your PR with excludable objects? 
I might merge it to current branch manually, if this is ready.

I took care of the public property issue.

**Comment by TomasVotruba** [comment]
Merged, thank you.

Feel free to

**Comment by TomasVotruba** [comment]
Todo:

- [ ] add configurable options to README with example
   see array: https://github.com/object-calisthenics/phpcs-calisthenics-rules/blob/4c0168fdb9ff6894db092998b2d7d312275d9b6c/src/ObjectCalisthenics/ruleset.xml#L73

**Pull request closed without merging**
