### PR TITLE
WIP - split method

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Had a go at splitting this method. Not easy, 11 vars in play, which get used and modified all over.

Looks like the (two different types?) of token could also use some encapsulation. Sure is confusing to me at present.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
How is this going? Maybe try smaller PR, we can merge that much faster.

**Comment by TomasVotruba** [comment]
Close due to no response timeout.

**Comment by JeroenDeDauw** [comment]
Could already have used the simplification I did so far...

**Comment by TomasVotruba** [comment]
Sure. Could you send PR to current master, please?

**Pull request closed without merging**
